version: '3.8'

services:
  gdrive-upload-service:
    build: .
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./rclone.conf:/root/.config/rclone/rclone.conf:ro
    restart: always
